version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - my-network

  app:
    build: .
    container_name: delhi-tourism-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/delhitourismdb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - mongo   

volumes:
  db_data:

networks:
  my-network:

  