apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tour-app-hpa
  namespace: delhi-tourism
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tour-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50